services:
  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - hotellaravel
    depends_on:
      php-fpm:
        condition: service_started


  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    user: postgres
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE:-app}
      - POSTGRES_USER=${DB_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - hotellaravel
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@example.com
    ports:
      - "105:80"
    networks:
      - hotellaravel

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: local
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    restart: unless-stopped
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www:rw
    networks:
      - hotellaravel


  redis:
    image: redis:alpine
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - hotellaravel

networks:
  hotellaravel:
volumes:
  postgres: